# -*- coding: utf-8 -*-
"""jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_appendix-tools-for-deep-learning/jupyter.ipynb
"""

import re
import random
import datetime

# basic chatbot using if else and regex patterns
# learned this from tutorial online

def get_response(user_input):
    msg = user_input.lower().strip()

    # greetings
    if re.search(r'hello|hi|hey', msg):
        return random.choice(["Hello!", "Hey there!", "Hi! How can I help?"])

    elif re.search(r'bye|goodbye|exit', msg):
        return "Goodbye! Have a nice day!"

    elif re.search(r'how are you|how r u', msg):
        return "I'm good! Just a bot though lol"

    elif re.search(r'your name|who are you', msg):
        return "I'm a simple chatbot made for my internship task :)"

    elif re.search(r'time|date', msg):
        now = datetime.datetime.now()
        return "Current time: " + now.strftime("%I:%M %p, %d %B %Y")

    elif re.search(r'joke', msg):
        jokes = [
            "Why do programmers hate nature? It has too many bugs!",
            "Why did the programmer quit? Because he didn't get arrays!",
            "I would tell a joke about UDP but you might not get it"
        ]
        return random.choice(jokes)

    elif re.search(r'thank|thanks|thx', msg):
        return "No problem!"

    elif re.search(r'help|what can you do', msg):
        return "I can chat with you! Try asking for a joke or say hello"

    elif re.search(r'wh?ea?th?er|temperature|forecast|climate', msg):
        return "I dont have internet access so cant check weather sorry"

    elif re.search(r'what can you do|what tasks|your tasks|capabilities|features|tell me what', msg):
        return "I can: answer greetings, tell jokes, show current time/date, and have a basic chat! Try saying hi or ask for a joke :)"

    elif re.search(r'who made you|who created you|who built you', msg):
        return "I was made as part of my CodSoft AI internship - Task 1!"

    elif re.search(r'age|how old', msg):
        return "I was just created today so pretty new haha"

    elif re.search(r'are you (a )?bot|are you (an )?ai|are you human|are you real', msg):
        return "Yes I am a bot! A simple rule based chatbot :)"

    elif re.search(r'what are you doing|what.?re you up to|you doing', msg):
        return random.choice([
            "Just sitting here waiting for someone to chat with haha",
            "Chatting with you! Thats about it lol",
            "Nothing much, just being a bot :)"
        ])

    elif re.search(r'location|where are you|where do you live|your place', msg):
        return "I dont have a physical location, I exist as a program on your computer!"

    elif re.search(r'what shall i do|what should i do|suggest something|give me advice|advise me', msg):
        return random.choice([
            "Maybe go for a walk? Or grab a coffee :)",
            "How about learning something new today!",
            "I'd suggest taking a break if you've been working hard!"
        ])

    elif re.search(r'good morning|good night|good evening|good afternoon', msg):
        return random.choice([
            "Good morning! Hope you have a great day!",
            "Hey! Hope you're doing well :)",
            "Good to see you!"
        ])

    elif re.search(r'what is your favorite|whats your fav|do you like|do you enjoy', msg):
        return "I'm just a bot so I don't really have preferences haha, but I enjoy chatting!"

    # if nothing matched
    else:
        return random.choice([
            "Hmm I dont understand that",
            "Can you rephrase that?",
            "I'm not sure what you mean",
            "Sorry I dont have a response for that yet"
        ])


def main():
    print("Simple Chatbot - Task 1")
    print("type bye to exit\n")

    while True:
        user_input = input("You: ")
        if not user_input:
            continue

        response = get_response(user_input)
        print("Bot:", response)

        if 'bye' in user_input.lower() or 'exit' in user_input.lower():
            break

if __name__ == "__main__":
    main()

